// Generated by RPG Maker MZ.
// Do not edit this file directly.
var $plugins =
[
{"name":"MultilingualSupport","status":true,"description":"[v1.0.0] Multilingual Support for Guardians of the Dafeng","parameters":"{\"defaultLanguage\":\"en\",\"showLanguageMenu\":\"true\"}"},
{"name":"GuardiansGameplay","status":true,"description":"[v1.0.0] Core Gameplay Systems for Guardians of the Dafeng","parameters":"{}"},
{"name":"InvestigationSystem","status":true,"description":"[v1.0.0] Investigation and Deduction System","parameters":"{}"},
{"name":"CultivationSystem","status":true,"description":"[v1.0.0] Cultivation and Breakthrough System","parameters":"{}"}
];
